package tools.followedwind.hibdbunit.test;

// Generated 2015/01/01 18:41:59 by Hibernate Tools 4.0.0

/**
 * Testtable generated by hbm2java
 */
@SuppressWarnings("serial") //add
public class TesttableCsv implements java.io.Serializable {

	private Integer id;
	private Integer score;

	public TesttableCsv() {
	}

	public TesttableCsv(Integer score) {
		this.score = score;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getScore() {
		return this.score;
	}

	public void setScore(Integer score) {
		this.score = score;
	}

}
