package tools.followedwind.hibdbunit.test;

// Generated 2015/01/01 18:41:59 by Hibernate Tools 4.0.0

/**
 * Testtable generated by hbm2java
 */
@SuppressWarnings("serial") //add
public class Testtable implements java.io.Serializable {

	private Integer id;
	private String data;

	public Testtable() {
	}

	public Testtable(String data) {
		this.data = data;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

}
